### ISSUE TITLE
add variables section

### ISSUE THREAD

**Issue by vsoch** [vsoch/gridtest#17]
We need a way to specify a variable that is used across grids and tests. it should be a section like:

```yaml
  # Variables can be used for grids or tests. The namespace is shared, variables looked for first.
  variables:

    generate_m:
      min: 0
      max: 2.0
      by: 0.1

    generate_N:
      min: 0
      max: 2.0
      by: 0.1
```
