### ISSUE TITLE
redo examples, docs with global grids

### ISSUE THREAD

**Issue by vsoch** [vsoch/gridtest#18]
e.g.

```
  grids:

    # This is a grid for the schrodinger class, but without extra examples
    schrodinger_inputs:
      args:
        m: 1.9
        N: [512, 2048, 4096] # If you wanted a list [[one, two, three], [one, two three]]
        dx: 1.5
        V0: 1.5
      functions:
        V_x: schrodinger_helpers.generate_V_x
        x: schrodinger_helpers.generate_x
        psi_x0: schrodinger_helpers.generate_psi_x0

```
