### ISSUE TITLE
To think about: should "private" classes be included?

### ISSUE THREAD

**Issue by vsoch** [vsoch/gridtest#2]
Currently, if we run `gridtest generate` for a module, it will include "private" functions, e.g., here is for python's default requests:

```yaml
$ cat requests-tests.yml 
requests:
  filename: /home/vanessa/anaconda3/lib/python3.7/site-packages/requests/sessions.py
  requests._check_cryptography:
  - args:
      cryptography_version: null
  requests.check_compatibility:
  - args:
      chardet_version: null
      urllib3_version: null
  requests.delete:
  - args:
      url: null
  requests.get:
  - args:
      params: null
      url: null
  requests.head:
  - args:
      url: null
  requests.options:
  - args:
      url: null
  requests.patch:
  - args:
      data: null
      url: null
  requests.post:
  - args:
      data: null
      json: null
      url: null
  requests.put:
  - args:
      data: null
      url: null
  requests.request:
  - args:
      method: null
      url: null
  requests.session:
  - args: {}
```

I think possibly private functions should be discluded by default, and only added if the user specifies to include them.
